import { ASSETS_BASE_URL } from "./config";

export const IMAGES = {
  logo: `${ASSETS_BASE_URL}/logo.svg`,
  landingImage: `${ASSETS_BASE_URL}/landing-image.svg`,
  aboutImage: `${ASSETS_BASE_URL}/about-image.svg`,
  serviceImage: `${ASSETS_BASE_URL}/service-image.svg`,
  logoMain: `${ASSETS_BASE_URL}/logo-main.svg`,
  cardImg1: `${ASSETS_BASE_URL}/homecard1.svg`,
  serviceHomeOrg: `${ASSETS_BASE_URL}/closets.svg`,
  serviceBathroom: `${ASSETS_BASE_URL}/bathroom-storage.svg`,
  serviceBuiltIns: `${ASSETS_BASE_URL}/built-ins.svg`,
  serviceCabinets: `${ASSETS_BASE_URL}/cabinets.svg`,
  serviceComCabinets: `${ASSETS_BASE_URL}/commercial-cabinets.svg`,
  serviceLaundary: `${ASSETS_BASE_URL}/laundry.svg`,
  serviceCloset: `${ASSETS_BASE_URL}/home-org.svg`,
  kitchenImg1: `${ASSETS_BASE_URL}/kitchen-img-1.png`,
  kitchenImg2: `${ASSETS_BASE_URL}/kitchen-img-2.png`,
  kitchenImg3: `${ASSETS_BASE_URL}/kitchen-img-3.png`,
  kitchenImg4: `${ASSETS_BASE_URL}/kitchen-img-4.png`,
  kitchenImg5: `${ASSETS_BASE_URL}/kitchen-img-5.png`,
  servicesImg1: `${ASSETS_BASE_URL}/services-img-1.png`,
  servicesImg2: `${ASSETS_BASE_URL}/services-img-2.png`,
  servicesImg3: `${ASSETS_BASE_URL}/services-img-3.png`,
  servicesImg4: `${ASSETS_BASE_URL}/services-img-4.png`,
  servicesImg5: `${ASSETS_BASE_URL}/services-img-5.png`,
  cabinetsImg3: `${ASSETS_BASE_URL}/cabinets-img-3.png`,
  closetsImg2: `${ASSETS_BASE_URL}/closets-img-2.png`,
  closetsImg3: `${ASSETS_BASE_URL}/closets-img-3.png`,
  bathroomImg1: `${ASSETS_BASE_URL}/bathroom-img-1.png`,
  bathroomImg2: `${ASSETS_BASE_URL}/bathroom-img-2.png`,
  bathroomImg3: `${ASSETS_BASE_URL}/bathroom-img-3.png`,
  bathroomImg4: `${ASSETS_BASE_URL}/bathroom-img-4.png`,
  blogImg1: `${ASSETS_BASE_URL}/blog1.png`,
  blogImg2: `${ASSETS_BASE_URL}/blog2.png`,
  blogImg3: `${ASSETS_BASE_URL}/blog3.png`,
  blogImg4: `${ASSETS_BASE_URL}/blog4.png`,
  blogImg5: `${ASSETS_BASE_URL}/blog5.png`,
  ArsalanAnwar: `${ASSETS_BASE_URL}/shani.jpg`,
  GhulamAhmed: `${ASSETS_BASE_URL}/sony.jpg`,
  GurvinderSingh: `${ASSETS_BASE_URL}/singh.jpg`,
};
